# Generated by Django 4.2 on 2023-04-21 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('europharm', '0005_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Userses',
        ),
    ]
