# Generated by Django 4.2 on 2023-04-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('europharm', '0006_rename_users_userses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userses',
            options={'verbose_name_plural': 'userses'},
        ),
        migrations.AddField(
            model_name='userses',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
