# Generated by Django 4.2 on 2023-04-21 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('europharm', '0007_alter_userses_options_userses_profile_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userses',
            new_name='Profile',
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'profiles'},
        ),
    ]
