# Generated by Django 4.2 on 2023-04-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('europharm', '0008_rename_userses_profile_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='instructions',
            field=models.FileField(default=None, upload_to='instructions/'),
        ),
    ]
