# Generated by Django 3.1.3 on 2023-05-14 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('europharm', '0013_auto_20230514_1919'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
