# Generated by Django 3.1.3 on 2023-05-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('europharm', '0016_auto_20230514_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
